name: 00 - Lint
permissions:
    contents: read # Default, but good to be explicit

on: [ push, pull_request ]

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/ruff-action@v3
